#:schema node_modules/wrangler/config-schema.json
name = "puppeteer-pdf-test"
main = "src/index.ts"
compatibility_date = "2024-04-05"
#compatibility_flags = [ "nodejs_compat" ]
node_compat = true
workers_dev = true


browser = { binding = "MYBROWSER" }
